### ISSUE TITLE
Solve capitalize algorithm

### ISSUE THREAD

**Issue by Vaibhav-Yadav-1998** [Vaibhav-Yadav-1998/JavaScript-Algorithms#13]
Create a function that takes an array of names and returns an array with the first letter capitalized.

### Examples
```
capitalize(["mavis", "senaida", "letty"]) ➞ ["Mavis", "Senaida", "Letty"]

capitalize(["samuel", "MABELLE", "letitia", "meridith"]) ➞ ["Samuel", "Mabelle", "Letitia", "Meridith"]

capitalize(["Slyvia", "Kristal", "Sharilyn", "Calista"]) ➞ ["Slyvia", "Kristal", "Sharilyn", "Calista"]
```
### Notes
Don't change the order of the original array.
Notice in the second example above, "MABELLE" is returned as "Mabelle".

After writing the solution run ```npm run capitalize-test``` to test your solution

**Please read the contribution guide before submitting your pull request**

**drop a comment here before submitting your pull request**

source: [edabit.com](https://edabit.com/challenge/ZN5cpGPNRS3nrjMo5)

**Comment by Ian-Yy** [comment]
Hi @Vaibhav-Yadav-1998 , May I try this?

**Comment by Vaibhav-Yadav-1998** [comment]
@Ian-Yy yes you can

**Comment by Kvek** [comment]
Can I claim this? I've written the solution.

**Comment by psalmfill** [comment]
can i clam this, solution written and test passed
